services:
  database:
    image: 'postgres:13-alpine3.21'
    restart: always
    environment:
      # please never ever do this outside of training! instead use real usernames and 
      # properly protected secret passwords.
      POSTGRES_USER: training
      POSTGRES_DB: training
      POSTGRES_HOST_AUTH_METHOD: trust
      # also not great for production, but this is training on a made-up dataset
      POSTGRES_WAL_LEVEL: minimal
    volumes:
      # csv files that will be imported to create database tables
      - ${PWD}/data/:/var/lib/postgresql/imports/
      # this sql will run when you start up the database
      - ${PWD}/startup:/docker-entrypoint-initdb.d

volumes:
  pgdata:
